#!/usr/bin/env python3
"""localize-machine — the game's strings through the estate's localization
lane: every source string goes through a live model call on the kumiki plane
(https://kumiki.catcave.dev/v1, Responses wire) with the itotori localizer
system prompt, producing assets/locales/ja.json. (The itotori leg of the
composite trial — content generated by the planes, in the game.)
"""
import json
import os
import sys
import time
import urllib.request

BASE_URL = os.environ.get("KUMIKI_BASE_URL", "https://kumiki.catcave.dev/v1")
MODEL = os.environ.get("KUMIKI_MODEL", "public-okay")
KEY_FILE = os.environ.get("KUMIKI_API_KEY_FILE", os.path.expanduser("~/.config/itotori/llm-api-key"))

SYSTEM = (
    "You are a professional English-to-Japanese game localizer working on a "
    "trials-style bicycle game titled 'Pelicans Riding Bicycles: A Feasibility "
    "Study' (a whimsical study of whether pelicans can ride bicycles; tone: "
    "deadpan institute report meets slapstick physics). Translate the user's "
    "string into natural Japanese. Rules: keep it concise and appropriate for "
    "a game UI; preserve placeholders like {n}; keep the ALL-CAPS weight for "
    "shouty strings (use katakana or kanji with emphasis); do NOT add quotes, "
    "romanization, notes, or explanations; output ONLY the translated string."
)


def extract_text(data):
    for item in data.get("output") or []:
        if item.get("type") == "message":
            for part in item.get("content") or []:
                if part.get("type") == "output_text":
                    return part.get("text") or ""
    return ""


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src = os.path.join(here, "..", "assets", "locales", "en.json")
    dst = os.path.join(here, "..", "assets", "locales", "ja.json")
    with open(src) as fh:
        en = json.load(fh)
    with open(KEY_FILE) as fh:
        api_key = fh.read().strip()

    ja = {}
    calls = []
    for i, (key, text) in enumerate(en.items()):
        if key in ("lang.en",):
            ja[key] = text  # language self-names stay
            continue
        body = json.dumps({
            "model": MODEL,
            "input": [
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": text},
            ],
            "max_output_tokens": 400,
            "temperature": 0.2,
        }).encode()
        req = urllib.request.Request(f"{BASE_URL}/responses", data=body, method="POST")
        req.add_header("Authorization", f"Bearer {api_key}")
        req.add_header("Content-Type", "application/json")
        out = None
        for attempt in range(3):
            try:
                with urllib.request.urlopen(req, timeout=90) as resp:
                    data = json.load(resp)
                out = extract_text(data).strip()
                rid = data.get("id")
                model = data.get("model")
                break
            except Exception as err:  # noqa: BLE001
                print(f"  [{key}] attempt {attempt + 1} failed: {err}", file=sys.stderr)
                time.sleep(3 * (attempt + 1))
        if out is None or not out:
            print(f"FAILED: {key}", file=sys.stderr)
            sys.exit(1)
        ja[key] = out
        calls.append({"key": key, "en": text, "ja": out, "response_id": rid, "served_model": model})
        print(f"[{i + 1}/{len(en)}] {key}: {text!r} -> {out!r}")

    with open(dst, "w") as fh:
        json.dump(ja, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    print(f"\nwrote {dst} ({len(ja)} strings, {len(calls)} live model calls)")


if __name__ == "__main__":
    main()
